### ISSUE TITLE
LoanRequest

### ISSUE THREAD

**Issue by Fraaktal** [Fraaktal/CultureBox#7]
LoanRequest : 
Id
IdBook
IdRequester
IdOwner
State = {Accepted, Refused, Pending, Ongoing, Ended}

Méthodes : 

GetAllRequests (3 modes all, only requests, only loans)
Test : Ok + BadRequest("INVALID_CREDENTIALS")

GetRequestById
Test : Ok + BadRequest("INVALID_CREDENTIALS") (invali apiKey) + NotFound (id not found) + BadRequest invalid credentials (l'id recherché ne concerne pas l'appelant avec son ApiKey il n'est ni l'emprunteur ni le préteur). 

RequestLoan
Test :  Ok + BadRequest("INVALID_CREDENTIALS") (invali apiKey) + BadRequest("INVALID_USER_ID"); (l'user a qui on veut emprunter n'existe pas) + BadRequest("BOOK_ALREADY_BORROWED"); le livre demandé est déjà emprunté (tester avec différents états et même avec un emprunt terminé pour ce même livre) + NotFound("MISSING_BOOK_IN_USER_COLLECTIONS"); le livre demandé n'existe pas dans la collection de l'user demandé.

UpdateLoanRequest
Test :  Ok + BadRequest("INVALID_CREDENTIALS") (invali apiKey) + NotFound(); + BadRequest("INVALID_CREDENTIALS"); le requester ne fait pas parti de l'emprunt (apikey)

**Comment by Fraaktal** [comment]
S'ajoute à cela :
SearchBookToBorrow
test : BadRequest("INVALID_PARAMETERS"); => title null ou vide + ok + notfound (aucune collection ne contient le livre recherché)

**Comment by zpaul91** [comment]
Done : 

- [x]  ; SearchBookToBorrow (3 tests, please fix the function) @Fraaktal 
- [x] GetAllRequests  (Only when 0 requests)

**Comment by Fraaktal** [comment]
Il manque :
GetRequestById
- [x] BadRequest("INVALID_CREDENTIALS"); => ApiKey existe pas
- [x] NotFound();
- [x] BadRequest("INVALID_CREDENTIALS"); => L'id passé n'appartient pas à l'user de l'apikey
- [x] Ok


UpdateLoanRequest
- [x] Ok
- [x] BadRequest("INVALID_CREDENTIALS") (invali apiKey) 
- [x] NotFound(); + 
- [x] BadRequest("INVALID_CREDENTIALS"); le requester ne fait pas parti de l'emprunt (apikey)


RequestLoan()
- [x] Livre => id user qu'on veut emprunter qu'oin recherche existe pas
- [x] Book already borrowed

- [x] tout tes tests pour le request book tu les faits pour les livres et séries
- [x] series => "House" et movies => "Harry Potter"

SearchObjectToBorrow
- [x] copier le test pour les books pour faire movies et series
